name = "edge-chat-demo"
compatibility_date = "2024-01-01"

main = "src/chat.mjs"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
  { name = "limiters", class_name = "RateLimiter" }
]

[ai]
binding = "AI"

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "RateLimiter"]

# Add the following section for local development
[dev]
port = 8787
